{
  "id": "uno-ooo-parser",
  "version": "0.1.20",
  "libre_office_ver": "7.2",
  "name": "ScanError",
  "type": "enum",
  "namespace": "com.sun.star.scanner",
  "parser_args": {
    "sort": true
  },
  "writer_args": {
    "include_desc": true
  },
  "data": {
    "name": "ScanError",
    "namespace": "com.sun.star.scanner",
    "url": "https://api.libreoffice.org/docs/idl/ref/namespacecom_1_1sun_1_1star_1_1scanner.html#abd1619ea132004db8599d9529755e9ab",
    "allow_db": true,
    "quote": [],
    "typings": [],
    "desc": "",
    "items": [
      {
        "name": "InvalidContext",
        "value": "InvalidContext",
        "desc": [
          "InvalidContext: a device was requested that does not exist."
        ]
      },
      {
        "name": "ScanCanceled",
        "value": "ScanCanceled",
        "desc": [
          "ScanCanceled: the scan was canceled by the user."
        ]
      },
      {
        "name": "ScanErrorNone",
        "value": "ScanErrorNone",
        "desc": [
          "ScanErrorNone: no error occurred."
        ]
      },
      {
        "name": "ScanFailed",
        "value": "ScanFailed",
        "desc": [
          "ScanFailed: an error occurred during scanning."
        ]
      },
      {
        "name": "ScanInProgress",
        "value": "ScanInProgress",
        "desc": [
          "ScanInProgress: a scan is already in progress on this device that has to end before a new one can be started."
        ]
      },
      {
        "name": "ScannerNotAvailable",
        "value": "ScannerNotAvailable",
        "desc": [
          "ScannerNotAvailable: the requested device could not be opened."
        ]
      }
    ]
  }
}