{
  "id": "uno-ooo-parser",
  "version": "0.1.8",
  "timestamp": "2021-12-28 10:14:22+00:00",
  "name": "BatchUpdateException",
  "type": "exception",
  "namespace": "com.sun.star.sdbc",
  "parser_args": {
    "sort": true
  },
  "writer_args": {
    "include_desc": true
  },
  "data": {
    "from_imports": [
      [
        ".sql_exception",
        "SQLException"
      ]
    ],
    "from_imports_typing": [],
    "quote": [],
    "typings": [],
    "requires_typing": false,
    "name": "BatchUpdateException",
    "namespace": "com.sun.star.sdbc",
    "imports": [],
    "extends": [
      "com.sun.star.sdbc.SQLException"
    ],
    "desc": [
      "is thrown when an error occurs during a batch update operation.",
      "",
      "In addition to the information provided by com.sun.star.sdbc.SQLException , a BatchUpdateException provides the update counts for all commands that were executed successfully during the batch update, that is, all commands that were executed before the error occurred. The order of elements in an array of update counts corresponds to the order in which commands were added to the batch."
    ],
    "url": "https://api.libreoffice.org/docs/idl/ref/exceptioncom_1_1sun_1_1star_1_1sdbc_1_1BatchUpdateException.html",
    "items": {}
  }
}