{
  "id": "uno-ooo-parser",
  "version": "0.1.15",
  "libre_office_ver": "7.2",
  "name": "GridInvalidDataException",
  "type": "exception",
  "namespace": "com.sun.star.awt.grid",
  "parser_args": {
    "sort": true,
    "long_names": true
  },
  "writer_args": {
    "include_desc": true
  },
  "data": {
    "from_imports": [
      [
        "...uno.runtime_exception",
        "RuntimeException",
        "uno_runtime_exception_i"
      ]
    ],
    "from_imports_typing": [],
    "extends_map": {
      "com.sun.star.uno.RuntimeException": "uno_runtime_exception_i"
    },
    "quote": [],
    "typings": [],
    "requires_typing": false,
    "name": "GridInvalidDataException",
    "namespace": "com.sun.star.awt.grid",
    "imports": [],
    "extends": [
      "com.sun.star.uno.RuntimeException"
    ],
    "desc": [
      "Exception is thrown to indicate that set data is invalid, e.g.",
      "",
      "type of data is unknown or data count doesn't match with column count.",
      "",
      "**since**",
      "",
      "    OOo 3.3"
    ],
    "url": "https://api.libreoffice.org/docs/idl/ref/exceptioncom_1_1sun_1_1star_1_1awt_1_1grid_1_1GridInvalidDataException.html",
    "items": {}
  }
}